# Header
menu:
  #暂不开放/Not Open: /
  日志 /Blog: /#blog  # "/#blog" is Enforced
  关于/About: /inner/about/
  归档/Archive: /archive

# I might forget to switch this from my blog version to public version,
# please switch it manually and issue it if it happened.

# Site favicon
favicon: /favicon.png

# Site logo
logo: /images/avatar.png

# Enable Mathjax
mathjax: false

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false

#-------------------- huno-clsblog Begin--------------------

post_comments: false
  #options
    # false : no comments
    # "manual" (or other string): you will config manually in comments.ejs
# [Available in config/theme/post]
#[In comments.ejs]
    
huno_clsblog_version_information: huno-clsblog V-0.1.1-dev.4
#printed on the footer of a page,if you don't like this , use 'false'
#[Available in theme]
#[In footer.ejs]

default_license_information: Copyright 2018
# this is not suggested for users to config , becasue it will change with the updates of the theme;
# This(default_license_information: "Copyright 2018") is NOT the license of this theme , which uses cc-by-nc-sa 4.0 license)
# [String] ,such as:
      # © 2016-2018
      # CC-BY 4.0 International
      # <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>
# [Available in config/theme/*post ] for post,use license_information: [String]
#[In footer.ejs]

hc_custom: glass
#choices:
  # false: None custom
  # other customs:(Rough)
    # glass
    # red_and_white
# [Available in config/theme/post]
# [In layout.ejs]

hc_bgm: false
#hc_bgm: 
  #false : No bgm
  #[String] : URL for your bgm (   http(s)://**.mp3  )
# [In side-panel.ejs]
# [Available in config/theme/post]

hc_iframe_bgm: false
# use bgm on side-panel by html code(yes,HTML code,but mostly <iframe>)
# You'd better mostly open one erither hc_bgm or hc_iframe_bgm
#hc_iframe_bgm: 
  #false : No iframe_bgm
  #[String] : HTML code for your bgm
# [In side-panel.ejs]
# [Available in config/theme/post]

# - hc_tech_filter:
#   tech knowledge filter for who can understand some html and usage of browsers' developer tool.
#   Funny Option in [post]

#-------------------- huno-clsblog End --------------------