# Header
menu:
  #暂不开放<br/>Not Open: /
  日志<br/>Blog: /#blog  # "/#blog" is Enforced
  关于<br/>About: /inner/about/
  归档<br/>Archive: /archive

# I might forget to switch this from my blog version to public version,
# please switch it manually and issue it if it happened.

# Site favicon
favicon: /favicon.png

# Site logo
logo: /images/avatar.png

# Enable Mathjax
mathjax: false

# Enable awesome-toc
awesome_toc: true

# Enable githubRepoWidget
github_repo_widget: false

#-------------------- huno-clsblog Begin--------------------LICENSE: CC-BY-NC-SA 4.0 International

hc_post_comments: false
  #options
    # false : no comments
    # gitment: use gitment
    # gitalk: use gitalk
    # manual: you will config manually in comments.ejs
# [Available in config/theme/post]
#[In comments.ejs]

hc_github_config: #must set hc_post_comments: gitment or gitalk,all below is enforced
  owner: 
  repo: 
  client_id: 
  client_secret: 
  admin: 
    - Tom
  
# [Available in theme]

hc_footer_info: huno-clsblog v0.1.2-dev.2 (Based on huno)
#printed on the footer of a page,if you don't like this , leave it nothing
#[Available in theme]
#[In footer.ejs]

default_license_information: ©Copyright 2018
# this is not suggested for users to config , becasue it will change with the updates of the theme;
# This(default_license_information: "Copyright 2018") is NOT the license of this theme , which uses cc-by-nc-sa 4.0 license)
# [String] ,such as:
  # CC-BY 4.0 International
  # Even HTML Code provided by CC
  # [Available in config/theme/*post ] 
  # for post,use license_information: [String]
#[In footer.ejs]

hc_custom: grace
#choices:
  # false: None custom
  # other customs:(Rough)
    # glass
    # red_and_white
    # grace
# [Available in config/theme/post]
# [In layout.ejs]

hc_bgm: false
#hc_bgm: 
  #false : No bgm
  #[String] : URL for your bgm (   http(s)://**.mp3  )
# [In side-panel.ejs]
# [Available in config/theme/post]

hc_panel_addition: false
# add some customed html in side-panel
# You'd better mostly open one erither hc_bgm or hc_iframe_bgm
# [In side-panel.ejs]
# [Available in config/theme/post]

# - hc_hide:
#   hide the page which can be seen by using develop tools(F12) to make it unhidden
#   Funny Option in [post]

# -------------Options End------------
# Updates
# Adjust
# Suggestions:
#   1.Use hexo-all-minifier(Plugin),
#     because I use too many /r/n in this theme's ejs files,which can casue your webpages become big and unstable
#   2.Add infomation such as 'Special Edition For XXX' to huno_clsblog_version_information:(if you make it not empty)
#   3.If you want to keep up-to-date,you need to know:
#     This theme DO NOT obey Semantic Versioning now(AT LEAST before 1.0.0)
#-------------------- huno-clsblog End --------------------
