#LICENSE: MPL 2.0
# Based on huno,uno
# All path here (exclude hc_social) must begin as "/"
# "tom" is a fake name,referring to no people

hc_menu:
  日志<br/>Blog: /#blog  # "/#blog" is Compulsory
  关于<br/>About: /about/
social:
    github: tom
#hc_social:
#  github.com: github.com/tom
# hc_social use favicon.ico of your social sites,so it support every site,but not stable

# You can still use huno's way to add social icons,which is stable,but don't use hc_social and social together.
# And,why not using a button on the menu?

# Site favicon
favicon: /favicon.ico

# Site logo
logo: /images/avatar.png

# Enable Mathjax
mathjax: false

# Enable awesome-toc
awesome_toc: false

# Enable githubRepoWidget
github_repo_widget: false

hc_post_comments: false
  #options
    # false : no comments
    # gitment: use gitment
    # vssue
    # gitalk: use gitalk (Recommended)
    # manual: config manually in comments.ejs

hc_github_config: #must set hc_post_comments: gitment, vssue, gitalk,all below is enforced
  owner: 
  repo: 
  client_id: 
  client_secret: 
  admin: #only for gitalk
    - tom
  type: github #or gitlab,bitbucket. only for vssue
  

hc_footer_info: hunoc 0.1.5-preview.1<br/>based on huno by letiantian,Powered by Hexo
#printed on the footer of a page,if you don't like this , leave it nothing
#[only available in theme]

default_license_information: ©Copyright 2018
# this is not suggested for users to config , becasue it will change with the updates of the theme;
# This(default_license_information: "Copyright 2018") is NOT the license of this theme , which uses cc-by-nc-sa 4.0 license)
# [String] ,such as:
  # CC-BY 4.0 International
  # Even HTML Code provided by CC
  # for post,use license_information: [String]

hc_custom: false
#choices:
  # false: None custom
  #(other): file name in /themes/hunoc/source/css/custom_uno/ 
  # huno: original huno look 

hc_panel_addition: false
# add some customed html in side-panel like bgm

# - hc_hide:
#   hide the page's content  
#   Funny Option in [post]

# Suggestions:
#   1.Use hexo-all-minifier(Plugin),
#   2.If you want to keep up-to-date,you need to know:
#     This theme DO NOT obey Semantic Versioning now(AT LEAST before 1.0.0)
#     This theme DO NOT update regular
#-------------------- hunoc End --------------------
# Updates
# recover social
# add huno custom
# Change background
# polish documets
# add local gitalk
# support vssue