#---hunoc---
#LICENSE: MPL 2.0
# Based on huno,uno
# All path here (exclude social) must begin as "/"
# config.root must end as "/"
hc_menu:
  日志<br/>Blog: /#blog  # "/#blog" is Compulsory
  关于<br/>About: /inner/about/
  归档<br/>Archive: /archive/
hc_social:
  #github.com: github.com/YourName

# Site favicon
favicon: /favicon.ico

# Site logo
logo: /images/avatar.png

# Enable Mathjax
mathjax: false

# Enable awesome-toc
awesome_toc: false

# Enable githubRepoWidget
github_repo_widget: false

hc_post_comments: false
  #options
    # false : no comments
    # gitment: use gitment
    # gitalk: use gitalk (Recommended)
    # manual: config manually in comments.ejs

hc_github_config: #must set hc_post_comments: gitment or gitalk,all below is enforced
  owner: 
  repo: 
  client_id: 
  client_secret: 
  admin: 
    - Tom

hc_footer_info: hunoc 0.1.3-dev.3<br/>based on huno by letiantian,Powered by Hexo
#printed on the footer of a page,if you don't like this , leave it nothing
#[Available in theme]
#[In footer.ejs]

default_license_information: ©Copyright 2018
# this is not suggested for users to config , becasue it will change with the updates of the theme;
# This(default_license_information: "Copyright 2018") is NOT the license of this theme , which uses cc-by-nc-sa 4.0 license)
# [String] ,such as:
  # CC-BY 4.0 International
  # Even HTML Code provided by CC
  # for post,use license_information: [String]
#[In footer.ejs]

hc_custom: false
#choices:
  # false: None custom
  # red_and_white
  # grace

hc_panel_addition: false
# add some customed html in side-panel
# You'd better mostly open one erither hc_bgm or hc_iframe_bgm

# - hc_hide:
#   hide the page which can be seen by using develop tools(F12) to make it unhidden
#   Funny Option in [post]

# Suggestions:
#   1.Use hexo-all-minifier(Plugin),
#     because I use too many /r/n in this theme's ejs files,which can casue your webpages become big and unstable
#   2.Add infomation such as 'Special Edition For XXX' to huno_clsblog_version_information:(if you make it not empty)
#   3.If you want to keep up-to-date,you need to know:
#     This theme DO NOT obey Semantic Versioning now(AT LEAST before 1.0.0)
#-------------------- huno-clsblog End --------------------
